// File generated by hadoop record compiler. Do not edit.
/**
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

using System;
#if !NET_CORE
using log4net;
#endif
using ZooKeeperNet.Jute;

namespace ZooKeeperNet.Generate
{
public class ConnectResponse : IRecord, IComparable 
{
    #if !NET_CORE
private static ILog log = LogManager.GetLogger(typeof(ConnectResponse));
#endif
  public ConnectResponse() {
  }
  public ConnectResponse(
  int protocolVersion
,
  int timeOut
,
  long sessionId
,
  byte[] passwd
) {
ProtocolVersion=protocolVersion;
TimeOut=timeOut;
SessionId=sessionId;
Passwd=passwd;
  }
  public int ProtocolVersion { get; set; } 
  public int TimeOut { get; set; } 
  public long SessionId { get; set; } 
  public byte[] Passwd { get; set; } 
  public void Serialize(IOutputArchive a_, String tag) {
    a_.StartRecord(this,tag);
    a_.WriteInt(ProtocolVersion,"protocolVersion");
    a_.WriteInt(TimeOut,"timeOut");
    a_.WriteLong(SessionId,"sessionId");
    a_.WriteBuffer(Passwd,"passwd");
    a_.EndRecord(this,tag);
  }
  public void Deserialize(IInputArchive a_, String tag) {
    a_.StartRecord(tag);
    ProtocolVersion=a_.ReadInt("protocolVersion");
    TimeOut=a_.ReadInt("timeOut");
    SessionId=a_.ReadLong("sessionId");
    Passwd=a_.ReadBuffer("passwd");
    a_.EndRecord(tag);
}
  public override String ToString() {
    try {
      System.IO.MemoryStream ms = new System.IO.MemoryStream();
      using(ZooKeeperNet.IO.EndianBinaryWriter writer =
        new ZooKeeperNet.IO.EndianBinaryWriter(ZooKeeperNet.IO.EndianBitConverter.Big, ms, System.Text.Encoding.UTF8)){
      BinaryOutputArchive a_ = 
        new BinaryOutputArchive(writer);
      a_.StartRecord(this,string.Empty);
    a_.WriteInt(ProtocolVersion,"protocolVersion");
    a_.WriteInt(TimeOut,"timeOut");
    a_.WriteLong(SessionId,"sessionId");
    a_.WriteBuffer(Passwd,"passwd");
      a_.EndRecord(this,string.Empty);
      ms.Position = 0;
      return System.Text.Encoding.UTF8.GetString(ms.ToArray());
    }    } catch (Exception ex) {
        #if !NET_CORE
      log.Error(ex);
      #endif
    }
    return "ERROR";
  }
  public void Write(ZooKeeperNet.IO.EndianBinaryWriter writer) {
    BinaryOutputArchive archive = new BinaryOutputArchive(writer);
    Serialize(archive, string.Empty);
  }
  public void ReadFields(ZooKeeperNet.IO.EndianBinaryReader reader) {
    BinaryInputArchive archive = new BinaryInputArchive(reader);
    Deserialize(archive, string.Empty);
  }
  public int CompareTo (object obj) {
    ConnectResponse peer = (ConnectResponse) obj;
    if (peer == null) {
      throw new InvalidOperationException("Comparing different types of records.");
    }
    int ret = 0;
    ret = (ProtocolVersion == peer.ProtocolVersion)? 0 :((ProtocolVersion<peer.ProtocolVersion)?-1:1);
    if (ret != 0) return ret;
    ret = (TimeOut == peer.TimeOut)? 0 :((TimeOut<peer.TimeOut)?-1:1);
    if (ret != 0) return ret;
    ret = (SessionId == peer.SessionId)? 0 :((SessionId<peer.SessionId)?-1:1);
    if (ret != 0) return ret;
    ret = Passwd.CompareTo(peer.Passwd);
    if (ret != 0) return ret;
     return ret;
  }
  public override bool Equals(object obj) {
 ConnectResponse peer = (ConnectResponse) obj;
    if (peer == null) {
      return false;
    }
    if (Object.ReferenceEquals(peer,this)) {
      return true;
    }
    bool ret = false;
    ret = (ProtocolVersion==peer.ProtocolVersion);
    if (!ret) return ret;
    ret = (TimeOut==peer.TimeOut);
    if (!ret) return ret;
    ret = (SessionId==peer.SessionId);
    if (!ret) return ret;
    ret = Passwd.Equals(peer.Passwd);
    if (!ret) return ret;
     return ret;
  }
  public override int GetHashCode() {
    int result = 17;
    int ret = GetType().GetHashCode();
    result = 37*result + ret;
    ret = (int)ProtocolVersion;
    result = 37*result + ret;
    ret = (int)TimeOut;
    result = 37*result + ret;
    ret = (int)SessionId;
    result = 37*result + ret;
    ret = Passwd.GetHashCode();
    result = 37*result + ret;
    return result;
  }
  public static string Signature() {
    return "LConnectResponse(iilB)";
  }
}
}
