version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.31.6"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/kafka/data:/kafka
  portal:
    image: dotnetspider/portal
    ports:
      - "7897:7896"
    volumes:
      - /Users/lewis/dotnetspider/portal/appsettings.json:/portal/appsettings.json
      - /Users/lewis/dotnetspider/portal/logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
  agent001:
    image: dotnetspider/downloader-agent
    environment:
      DOTNET_SPIDER_AGENTID: "Agent001"
      DOTNET_SPIDER_AGENTNAME: "Agent001"
      DOTNET_SPIDER_KAFKACONSUMERGROUP: "Agent"
      DOTNET_SPIDER_KafkaBootstrapServers: "192.168.31.6:9092"
    volumes:
      - /Users/lewis/dotnetspider/agent/logs:/logs
  agent002:
    image: dotnetspider/downloader-agent
    environment:
      DOTNET_SPIDER_AGENTID: "Agent002"
      DOTNET_SPIDER_AGENTNAME: "Agent002"
      DOTNET_SPIDER_KAFKACONSUMERGROUP: "Agent"
      DOTNET_SPIDER_KafkaBootstrapServers: "192.168.31.6:9092"
    volumes:
      - /Users/lewis/dotnetspider/agent/logs:/logs    